import SinglePost from '@/components/Post/SinglePost';
import {} from '../../../../lib/notionAPI';
import Head from 'next/head';
import Pagenation from '@/components/Pagenation/Pagenation';

const BlogTagPageList = ({ numberOfPage, posts }: any) => {
  return (
    <div className='container mx-auto h-full w-full'>
      <Head>
        <title>Notion-Blog</title>
        <meta name='description' content='Generated by create nextapp' />
        <link rel='icon' href='/favicon.icon' />
      </Head>

      <main className='w-ful container mt-16'>
        <h1 className='mb-16 text-center text-5xl font-medium'>
          Notion Blog🚀
        </h1>
        <section className=' sm:grid  grid-cols-2 w:5/6 gap-4 mx-auto'>
          {posts.map((post: any) => (
            <div key={post.id}>
              <SinglePost
                title={post.title}
                description={post.description}
                date={post.date}
                tags={post.tags}
                slug={post.slug}
                isPaginationPage={true}
              />
            </div>
          ))}
        </section>
        <Pagenation numberOfPage={numberOfPage} />
      </main>
    </div>
  );
};

export default BlogTagPageList;
